catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDetailView, BlogListView, BlogDetailView, BlogCreateView, \
    BlogUpdateView, BlogDeleteView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', contacts, name='contacts'),
    path('view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view_product'),
    path('product/create/', ProductCreateView.as_view(), name='create_product'),
    path('product/edit/<int:pk>/', ProductUpdateView.as_view(), name='edit_product'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),

    path('blog/create/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/', BlogListView.as_view(), name='list_blog'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='view_blog'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, generate_new_password, verify

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
    path('verify/', verify)
]

catalog/models.py
from django.conf import settings
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='изображение')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена')
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name="Опубликовано")


    def __str__(self):
        return f'{self.name}, {self.category}, {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    date_creation = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.TextField(verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии', unique=True)
    version_flag = models.BooleanField(default=True, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.version_number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CatalogForms(StyleFormMixin, forms.ModelForm):
    error_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар', ]

    class Meta:
        model = Product
        exclude = ('owner', 'is_active')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        if cleaned_data in self.error_list:
            raise forms.ValidationError('Запрещенное название')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        if cleaned_data in self.error_list:
            raise forms.ValidationError('Запрещенное описание')

        return cleaned_data


class ModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields["is_active"].widget.attrs['class'] = 'form-check-input'


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import CatalogForms, VersionForm, ModeratorForm
from catalog.models import Product, Blog, Version
from catalog.services import get_categories


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['categories'] = get_categories()
        return context_data

class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = CatalogForms
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = CatalogForms
    success_url = reverse_lazy('catalog:index')

    def get_form_class(self):
        if self.request.user.groups.filter(name='mod').exists():
            return ModeratorForm
        else:
            return CatalogForms

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.request.user.groups.filter(name='mod').exists() or self.request.user.is_superuser:
            return self.object
        if self.object.owner != self.request.user:
            raise Http404
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data



    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')
    return render(request, 'catalog/contacts.html')


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview', 'is_published')
    success_url = reverse_lazy('catalog:list_blog')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'preview', 'is_published')

    # success_url = reverse_lazy('catalog:list_blog')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:view_blog', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:list_blog')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BestShop</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_catalog_menu.html' %}
{% block content %}
{% endblock %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                BestShop
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить запись "{{ object.title }}"</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'catalog:list_blog' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content%}

<h2 class="display-4">Blog</h2>


<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{blog.title|title}} "{{object.slug}}"</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title"></h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{blog.body}}</li><br>
                        <img class="primary-img" src="/media/{{ object.preview }}" style="width: 400px; height: 350px">
                        <li>Дата создания - {{blog.date_creation}}</li>
                    </ul>
                    <div class="card-footer">
                        Просмотры {{ object.views_count }}
                    </div>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                    href="{% url 'catalog:list_blog' %}">К списку</a>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content%}

<h1 class="display-4">Blogs</h1>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_blog' %}">Добавить Блог</a>
</div>


<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.title|title}}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title"></h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li></li><br>
                        <li>- {{object.body|slice:":100"}}</li>
                    </ul>
                    </div>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:view_blog' object.pk %}"
                           type="button" class="btn btn-sm btn-outline-secondary">View</a>
                        <a href="{% url 'catalog:edit_blog' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'catalog:delete_blog' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-danger">Delete</a>
                </div>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content%}

<h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                    </form>

                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправит</button>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content%}

<h1 class="display-4">BestShop</h1>



<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.name|title}}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ {{object.price}}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Категория :{{object.category}}</li><br>
                        <li>- {{object.description|slice:":100"}}</li>
                    </ul>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product' object.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}

{% block content%}

<h1 class="display-4">BestShop</h1>


<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{product.name|title}}</h4>
                </div>
                <div class="card-body">
                    <img class="primary-img" src="{{ product.image.url }}" style="width: 400px; height: 350px">
                    <h1 class="card-title pricing-card-title">Цена - {{product.price}}$ </h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Категория - {{product.category}}</li><br>
                        <li>Описние</li>
                        <li>{{product.description}}</li><br>
                        <li>Дата создания - {{product.date_creation}}</li>
                        <li>Дата изменения- {{product.date_modification}}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить запись "{{ object.name }}"</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'catalog:index' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content%}

<h1 class="display-4">BestShop</h1>


<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{product.name|title}}</h4>
                </div>
                <div class="card-body">
                    <img class="primary-img" src="{{ object.image|mymedia }}" style="width: 400px; height: 350px">
                    <h1 class="card-title pricing-card-title">Цена - {{product.price}}$ </h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Категория - {{product.category}}</li><br>
                        <li>Описние</li>
                        <li>{{product.description}}</li><br>
                        <li>Дата создания - {{product.date_creation}}</li>
                        <li>Дата изменения- {{product.date_modification}}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование
                {% else %}
                Создание
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Версия
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content%}

<h1 class="display-4">BestShop</h1>



<div class="container">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.name|title}}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ {{object.price}}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Категория :{{object.category}}</li><br>
                        <li> {{object.description|slice:":100"}}</li>
                        <br>
                        <li>Пользователь: {{object.owner.first_name|default:"-------"}}</li>
                    </ul>
                    <div class="btn-group">
                        <a href="{% url 'catalog:view_product' object.pk %}"
                           type="button" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                        <a href="{% url 'catalog:edit_product' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Редактировать</a>
                        <a href="{% url 'catalog:delete_product' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}